### ISSUE TITLE
Allow specifying from_addr and to_addr for applications

### ISSUE THREAD

**Issue by hackel** [mariodpros/ufw-formula#3]
It would be very nice if we could easily configure ufw applications like:

``` yaml
ufw:
  applications:
    Salt:
      from_addr:
        - 10.0.0.0/8
      to_addr: 10.0.2.1      
```

I know in this case it's trivial to do with explicit port numbers, but this way if the package changes ports for whatever reason, the salt pillar need not be updated.
